In [ ]:
#VIDHYASHREE G S -AMB2292

In [ ]:
import pandas as pd
prod=pd.Series([ 30,60,45,25],
      index=["wheat","rice","maize","barley"])  # we can create out own indexes in pandas
print(prod)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
print(prod["rice"])
print(prod.loc["rice"])   # loc is used to get index

60
60

In [ ]:
#by position
print(prod.iloc[0])
print(prod.iloc[1])  # i loc is used with index is used

30
60

In [ ]:
print(prod.sum())
print(prod.mean())
print(prod.max())  # it gives max index values

print(prod.idxmax()) # it gives ,max production crop

160
40.0
60
rice

In [ ]:
#increase all crop production by 10%
increased_prod=prod*1.10
print(increased_prod)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
# crops with having greater than 40 tons
high_prod =prod[prod>40] #inner prod gives true or false and outer prod is used to store whih as true value
print(high_prod)
print()
print(prod>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
df=pd.DataFrame({
    "name":["akhil","bobby","charran"],
    "age":[25,30,35],
    "city":["ny","la","chicago"]
},index=["a","b","c"])

print(df)
print()
print(df.loc["b"])

      name  age     city
a    akhil   25       ny
b    bobby   30       la
c  charran   35  chicago

name    bobby
age        30
city       la
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])    #to analyse only name and city

      name  age     city
a    akhil   25       ny
b    bobby   30       la
c  charran   35  chicago

      name     city
a    akhil       ny
c  charran  chicago

In [ ]:
print(df.loc[df["age"]>28,["name","age"]])

      name  age
b    bobby   30
c  charran   35

In [ ]:
print(df.iloc[[0,2]])

      name  age     city
a    akhil   25       ny
c  charran   35  chicago

In [ ]:
print(df.iloc[[0,2],[1,2]])  #select rows and columns

   age     city
a   25       ny
c   35  chicago

In [ ]:
import pandas as pd
data={
    "farm":["farmA","farmB","farmC","farmD"],
    "crop":["wheat","rice","wheat","maize"],
    "area_hectares":[10,15,8,12],
    "production":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

    farm   crop  area_hectares  production
0  farmA  wheat             10          30
1  farmB   rice             15          60
2  farmC  wheat              8          24
3  farmD  maize             12          36

In [ ]:
df.head()     #top rows

    farm   crop  area_hectares  production
0  farmA  wheat             10          30
1  farmB   rice             15          60
2  farmC  wheat              8          24
3  farmD  maize             12          36

In [ ]:
df.head(2)

    farm   crop  area_hectares  production
0  farmA  wheat             10          30
1  farmB   rice             15          60

In [ ]:
df.tail(2)  #bottom rows

    farm   crop  area_hectares  production
2  farmC  wheat              8          24
3  farmD  maize             12          36

In [ ]:
df.info()  #gives basic information about prg

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   farm           4 non-null      object
 1   crop           4 non-null      object
 2   area_hectares  4 non-null      int64
 3   production     4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()  #basic summary in the form of stastics

       area_hectares  production
count       4.000000    4.000000
mean       11.250000   37.500000
std         2.986079   15.779734
min         8.000000   24.000000
25%         9.500000   28.500000
50%        11.000000   33.000000
75%        12.750000   42.000000
max        15.000000   60.000000

In [ ]:
df["yield_ton_per_hectare"]=df["production"]/df["area_hectares"]   #adding a new column to the existing one=
print(df)

    farm   crop  area_hectares  production  yield_ton_per_hectare
0  farmA  wheat             10          30                    3.0
1  farmB   rice             15          60                    4.0
2  farmC  wheat              8          24                    3.0
3  farmD  maize             12          36                    3.0

In [ ]:
df.iloc[[1,3]]

    farm   crop  area_hectares  production  yield_ton_per_hectare
1  farmB   rice             15          60                    4.0
3  farmD  maize             12          36                    3.0

In [ ]:
df.iloc[[1,3],[0,1,2]]     #itwrks with only integers not string

    farm   crop  area_hectares
1  farmB   rice             15
3  farmD  maize             12

In [ ]:
df.loc[[1,3],["farm","crop","area_hectares"]]    # mixing is done for  both integer and string

    farm   crop  area_hectares
1  farmB   rice             15
3  farmD  maize             12

In [ ]:
print(df["crop"]=="wheat")
print()                              #i want only wheat rows and storte it as wheat_farm
wheat_farm=df[df["crop"]=="wheat"]
print(wheat_farm)

0     True
1    False
2     True
3    False
Name: crop, dtype: bool

    farm   crop  area_hectares  production  yield_ton_per_hectare
0  farmA  wheat             10          30                    3.0
2  farmC  wheat              8          24                    3.0

In [ ]:
#farms with yield greater than 3
high_yield=df[df["yield_ton_per_hectare"]>3]
print(high_yield)

    farm  crop  area_hectares  production  yield_ton_per_hectare
1  farmB  rice             15          60                    4.0

In [ ]:
#sort the forms by highest production
sorted_df=df.sort_values(by="production",ascending=False)
print(sorted_df)

    farm   crop  area_hectares  production  yield_ton_per_hectare
1  farmB   rice             15          60                    4.0
3  farmD  maize             12          36                    3.0
0  farmA  wheat             10          30                    3.0
2  farmC  wheat              8          24                    3.0

In [ ]:
#groupby operation -average yield per crop
avg_yield=df.groupby("crop")["yield_ton_per_hectare"].mean()
print(avg_yield)
avg_yield=df.groupby("crop")["yield_ton_per_hectare"].sum()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    3.0
Name: yield_ton_per_hectare, dtype: float64
crop
maize    3.0
rice     4.0
wheat    6.0
Name: yield_ton_per_hectare, dtype: float64